version: '3.3'
services:
    mysql:
        container_name: "mysql"
        image: mysql:5.7
        volumes:
            - ./oai_db2.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./mysql-healthcheck2.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.131
networks:
     public_net:
         external:
             name: demo-oai-public-net
    #public_net:
    #    driver: bridge
    #    name: demo-oai-public-net
    #    ipam:
    #        config:
    #            - subnet: 192.168.70.128/26
    #    driver_opts:
    #        com.docker.network.bridge.name: "demo-oai"
