apiVersion: v2
name: oai-gnbsim
description: A Helm chart for gnbsim

type: application

icon: http://www.openairinterface.org/wp-content/uploads/2015/06/cropped-oai_final_logo.png

version: 0.1.0

appVersion: onap-0.1.0

keywords:
  - 5GCN
  - Gnbsim

sources:
  - https://github.com/hhorai/gnbsim
  - https://gitlab.eurecom.fr/kharade/gnbsim

maintainers:
  - name:  OPENAIRINTERFACE
    email: rohan.kharade@openairinterface.org
