version: '3.8'

services:
    enb:
        image: oai-enb:develop
        privileged: true
        container_name: rfsim4g-oai-enb
        networks:
            public_net:
                ipv4_address: 192.168.61.20
        environment:
            TZ: Europe/Paris
            USE_FDD_MONO: 'yes'
            RFSIMULATOR: enb
            ENB_NAME: eNB-rf-sim
            MCC: '208'
            MNC: '96'
            MNC_LENGTH: 2
            TAC: 1
            UTRA_BAND_ID: 7
            DL_FREQUENCY_IN_MHZ: 2680
            UL_FREQUENCY_OFFSET_IN_MHZ: 120
            NID_CELL: 10
            NB_PRB: 25
            MME_S1C_IP_ADDRESS: 192.168.61.3
            ENB_S1C_IF_NAME: eth0
            ENB_S1C_IP_ADDRESS: 192.168.61.20
            ENB_S1U_IF_NAME: eth0
            ENB_S1U_IP_ADDRESS: 192.168.61.20
            ENB_X2_IP_ADDRESS: 192.168.61.20
            FLEXRAN_ENABLED: 'no'
            FLEXRAN_INTERFACE_NAME: eth0
            FLEXRAN_IPV4_ADDRESS: 192.168.61.10
            USE_ADDITIONAL_OPTIONS: --rfsim --log_config.global_log_options level,nocolor,time --noS1
        healthcheck:
            test: /bin/bash -c "pgrep lte-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai_ue0:
        image: oai-lte-ue:develop
        privileged: true
        container_name: rfsim4g-oai-lte-ue0
        networks:
            public_net:
                ipv4_address: 192.168.61.30
        expose:
            - "10000"
        environment:
            TZ: Europe/Paris
            HOSTNAME: oai_ue0
            RFSIMULATOR: 192.168.61.20
            MCC: '208'
            MNC: '96'
            SHORT_IMSI: '0100000001'
            LTE_KEY: 'fec86ba6eb707ed08905757b1bb44b8f'
            OPC: 'c42449363bbad02b66d16bc975d77cc1'
            MSISDN: '001011234561010'
            HPLMN: 20896
            USE_ADDITIONAL_OPTIONS: --rfsim -C 2680000000 -r 25 --ue-rxgain 140 --ue-txgain 120 --nokrnmod 1 --log_config.global_log_options level,nocolor,time --noS1
        healthcheck:
            test: /bin/bash -c "pgrep lte-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        name: rfsim4g-oai-public-net
        ipam:
            config:
                - subnet: 192.168.61.0/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim4g-public"
