version: '3.8'

services:
    gnb_mono_tdd:
        image: oai-gnb:latest
        privileged: true
        container_name: sa-b200-gnb
        environment:
            USE_SA_TDD_MONO_B2XX: 'yes'
            USE_B2XX: 'yes'
            GNB_NAME: gNB-in-docker
            MCC: '222'
            MNC: '01'
            MNC_LENGTH: 2
            TAC: 1
            NSSAI_SST: 1
            NSSAI_SD0: 1
            AMF_IP_ADDRESS: 172.21.16.136
            GNB_NGA_IF_NAME: eth0
            GNB_NGA_IP_ADDRESS: 192.168.68.194
            GNB_NGU_IF_NAME: eth0
            GNB_NGU_IP_ADDRESS: 192.168.68.194
            USE_ADDITIONAL_OPTIONS: --sa -E -q --RUs.[0].sdr_addrs serial=30C51D4 --continuous-tx --log_config.global_log_options level,nocolor,time,line_num,function
        volumes:
            - /dev:/dev
        networks:
            public_net:
                ipv4_address: 192.168.68.194
        #entrypoint: /bin/bash -c "sleep infinity"
        healthcheck:
            # pgrep does NOT work
            test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        name: sa-b200-gnb-net
        ipam:
            config:
                - subnet: 192.168.68.192/26
        driver_opts:
            com.docker.network.bridge.name: "sa-gnb-net"
