version: '3.8'

services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.74.191

    oai-nrf:
        container_name: "oai-nrf"
        image: oai-nrf:develop
        environment:
            - NRF_INTERFACE_NAME_FOR_SBI=eth0
            - NRF_INTERFACE_PORT_FOR_SBI=80
            - NRF_INTERFACE_HTTP2_PORT_FOR_SBI=9090
            - NRF_API_VERSION=v1
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
        networks:
            public_net:
                ipv4_address: 192.168.74.192
        healthcheck:
            test: /bin/bash -c "pgrep nrf"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-smf:
        container_name: oai-smf
        image: oai-smf:develop
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.74.196
        environment:
            INSTANCE: 1
            PID_DIRECTORY: /var/run
            SMF_INTERFACE_NAME_FOR_N4: eth0
            SMF_INTERFACE_NAME_FOR_SBI: eth0
            SMF_INTERFACE_PORT_FOR_SBI: 80
            SMF_INTERFACE_HTTP2_PORT_FOR_SBI: 8080
            SMF_API_VERSION: v1
            DEFAULT_DNS_IPV4_ADDRESS: 8.8.8.8
            DEFAULT_DNS_SEC_IPV4_ADDRESS: 8.8.4.4
            UE_IP_ADDRESS_POOL: '12.1.1.2 - 12.1.1.200'
            AMF_IPV4_ADDRESS: 192.168.74.195
            AMF_PORT: 80
            AMF_API_VERSION: v1
            UDM_IPV4_ADDRESS: 192.168.74.194
            UDM_PORT: 80
            UDM_API_VERSION: v1
            UPF_IPV4_ADDRESS: 192.168.74.197
            USE_NETWORK_INSTANCE: 'no'
            NRF_API_VERSION: 'v1'
            NRF_IPV4_ADDRESS: '127.0.0.1'
            NRF_PORT: '8080'
            REGISTER_NRF: 'yes'
            DISCOVER_UPF: 'yes'
        healthcheck:
            test: /bin/bash -c "pgrep oai_smf"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-amf:
        container_name: oai-amf
        image: oai-amf:develop
        depends_on: [oai-nrf, mysql, oai-smf]
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.74.195
        environment:
            INSTANCE: 1
            PID_DIRECTORY: /var/run
            MCC: '208'
            MNC: '95'
            REGION_ID: '128'
            AMF_SET_ID: 1
            SERVED_GUAMI_MCC_0: '208'
            SERVED_GUAMI_MCC_1: '460'
            SERVED_GUAMI_MNC_0: '95'
            SERVED_GUAMI_MNC_1: '11'
            SERVED_GUAMI_REGION_ID_0: '95'
            SERVED_GUAMI_REGION_ID_1: '11'
            SERVED_GUAMI_AMF_SET_ID_0: '1'
            SERVED_GUAMI_AMF_SET_ID_1: '1'
            PLMN_SUPPORT_MCC: '208'
            PLMN_SUPPORT_MNC: '95'
            PLMN_SUPPORT_TAC: '0xa000'
            SST_0: '222'
            SST_1: '1'
            SD_0: '123'
            SD_1: '12'
            SMF_SELECTION: 'yes'
            SMF_INSTANCE_ID_0: 1
            SMF_INSTANCE_ID_1: 2
            SMF_IPV4_ADDR_0: 192.168.74.196
            SMF_IPV4_ADDR_1: 127.0.0.1
            SMF_HTTP_VERSION_0: v1
            SMF_HTTP_VERSION_1: v1
            AMF_INTERFACE_NAME_FOR_NGAP: eth0
            AMF_INTERFACE_NAME_FOR_N11:  eth0
            AUSF_IPV4_ADDRESS: 192.168.74.193
            AUSF_API_VERSION: 'v1'
            AUSF_PORT: 80
            NRF_IPV4_ADDRESS: 192.168.74.192
            NRF_API_VERSION: 'v1'
            NRF_PORT: 80
            MYSQL_SERVER: 192.168.74.191
            MYSQL_USER: 'root'
            MYSQL_PASS: 'linux'
            MYSQL_DB: 'oai_db'
            OPERATOR_KEY: '63bfa50ee6523365ff14c1f45f88737d'
            NF_REGISTRATION: 'yes'
        healthcheck:
            test: /bin/bash -c "pgrep oai_amf"
            interval: 10s
            timeout: 5s
            retries: 5    

    oai-spgwu:
        container_name: oai-spgwu
        image: oai-spgwu-tiny:gtp_extension_header
        depends_on: [oai-amf]
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.74.197
        environment:
            INSTANCE: 1
            PID_DIRECTORY: /var/run
            SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP: "eth0"
            SGW_INTERFACE_NAME_FOR_SX: "eth0"
            PGW_INTERFACE_NAME_FOR_SGI: "eth0"
            SPGWC0_IP_ADDRESS: "192.168.74.196"
            NETWORK_UE_IP: "12.1.1.0/24"
            NETWORK_UE_NAT_OPTION: "yes"
            REGISTER_NRF: "yes"
            NRF_IPV4_ADDRESS: "192.168.74.192"
            NRF_PORT: "8080"
            NRF_API_VERSION: "v1"
            GW_ID: "1"
            MNC03: "95"
            MCC: "208"
            REALM: "3gppnetwork.org"
            THREAD_S1U_PRIO: "64"
            S1U_THREADS: "1"
            THREAD_SX_PRIO: "64"
            SX_THREADS: "1"
            THREAD_SGI_PRIO: "64"
            SGI_THREADS: "1"
            GTP_EXTENSION_HEADER_PRESENT: "no"
            BYPASS_UL_PFCP_RULES: "no"
        healthcheck:
            test: /bin/bash -c "pgrep spgwu"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nat:
        container_name: oai-nat
        image: ubuntu:bionic
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.74.205
        entrypoint: /bin/bash -c \
              "apt update; apt install -y iptables iproute2 iputils-ping net-tools python iperf3;"\
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.1.1.0/24 via 192.168.74.197 dev eth0; sleep infinity"
        healthcheck:
            test: /bin/bash -c "ping -c 3 12.1.1.2"
            interval: 10s
            timeout: 5s
            retries: 5

    gnbsim:
        container_name: gnbsim
        image: gnbsim:develop
        depends_on: [oai-amf, oai-nat]
        privileged: true
        environment:
            MCC: 208
            MNC: 95
            GNBID: 1
            TAC: '0x00a000'
            SST: '222'
            SD: '010203'
            SD_UE_PARAM: '00007b'
            PagingDRX: 'v32'
            RANUENGAPID: 0
            IMEISV: '35609204079514'
            MSIN: '0000000031'
            RoutingIndicator: 1234
            ProtectionScheme: 'null'
            KEY: '0C0A34601D4F07677303652C0462535B'
            OPc: '63bfa50ee6523365ff14c1f45f88737d'
            DNN: 'default'
            URL: 'http://192.168.74.205:8000'
            NRCellID: 1
            USE_FQDN: 'no'
            NGAPPeerAddr: '192.168.74.195'
            GTPuLocalAddr: '192.168.74.198' # spgwu-tiny-upf
            GTPuIFname: 'eth0'
        networks:
            public_net:
                ipv4_address: 192.168.74.198
        healthcheck:
            test: /bin/bash -c "ifconfig gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        name: oai-public-net
        ipam:
            config:
                - subnet: 192.168.74.0/24
